### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by jonrrivera** [sanity-io/hydrogen-sanity-demo#105]
would love to start building using remix, sanity and hydrogen. But I keep getting into this error when `yarn dev` my app for the first time. Any pointers ?

<img width="850" alt="Screenshot 2023-11-29 at 11 42 27 AM" src="https://github.com/sanity-io/hydrogen-sanity-demo/assets/18686388/46532313-4794-42f1-90ae-7108e75058ed">

**Comment by kmelve** [comment]
HI! We're working on updating this starter as we speak. The challenge here is that the `apiVersion` in the client isn't configured beyond `v2021-03-25` (the error message says it's running against `v1`). 

I believe the `apiVersion` is set here: https://github.com/sanity-io/hydrogen-sanity-demo/blob/4bfe59aa88cba9672c58319a4596737462158137/server.ts#L75

**Comment by jonrrivera** [comment]
thank you! I was able to compile by commending off `perspective: 'published'` in the server.ts file for the moment


```
        config: {
          projectId: env.SANITY_PROJECT_ID,
          dataset: env.SANITY_DATASET,
          apiVersion: env.SANITY_API_VERSION ?? '2023-03-30',
          useCdn: process.env.NODE_ENV === 'production',
          // perspective: 'published',
        },
```

**Comment by thebiggianthead** [comment]
Just updated this repo to latest Remix / Hydrogen versions. We will likely update `hydrogen-sanity` to support our new Presentation tool in the future so keep your eyes peeled for that!

In the meantime, I'll mark this issue as closed as the fallback API version in the repo supports perspectives, and this issue is solved by using the supported API versions.
