### ISSUE TITLE
BuyNowButton doesn't add attributes that were added to the lines

### ISSUE THREAD

**Issue by FilipLjubic** [sanity-io/hydrogen-sanity-demo#82]
Example of my buy button

```js

<BuyNowButton
        lines={[
          {
            merchandiseId: selectedVariant!.id,
            quantity: 1,
            attributes: [{key: 'test', value: 'test'}],
          },
        ]}
        disabled={!selectedVariant || isOutOfStock}
/>

```

**Comment by thebiggianthead** [comment]
The `<BuyNowButton />` component is a link to the `($lang).cart.$lines.tsx` route, which is modelled similarly to Shopify's own [Demo Store template](https://github.com/Shopify/hydrogen/blob/2023-04/templates/demo-store/app/routes/(%24locale).cart.%24lines.tsx). This route accepts `<variant_id>:<quantity>` in the URL (split by a comma) and currently doesn't support attributes. You'd need to amend the behaviour in order to support this - either to add additional data into the URL or by adding to cart async with the button before redirecting to checkout.

**Comment by FilipLjubic** [comment]
Hey! I forgot I opened this. I fixed it in my store by adding the attributes as search params and handling them in the `cart .$lines` route. Would this be something that you guys would like implemented in this demo or are you happy with the way things are currently?
