### ISSUE TITLE
Deployment on Netlify

### ISSUE THREAD

**Issue by benitodotcool** [sanity-io/hydrogen-sanity-demo#9]
### Hello,

> First of all thank you for this template, I plan to use it regularly from now on because it suits perfectly what I want to produce in the future.

I don't know if this is the place to post this message but I'll try anyway.

Everything works perfectly on my localhost, I managed to connect a Shopify store, to create my content as I want etc. However, when I want to put this project online (I followed the official Netlify documentation), I get the `Page not found` page even though I'm at the root of the URL (in localhost I have the homepage with my elements, my menu, etc.).

I have the impression that the connection with Sanity is not done in production when Netlify runs the 'npm run build' command. I don't know Netlify at all, it's the first time I want to use it and so I'm a bit lost! I used Heroku for a long time and I had to add environment variables for production. I suppose that it is the same manipulation, but I do not find anything on Internet because this template is relatively recent.

Thanks for your help,
All the best,

@benitodotcool

**Comment by axeldurand3** [comment]
Hello,

I solved this problem with this topic : https://answers.netlify.com/t/query-sanity-from-netlify-edge-function/71175

The problem is the package @sanity/client. It didn't work with Netlify Edge functions.
You need to use picosanity instead: https://github.com/rexxars/picosanity

Then modify these variables in your components and it should works !

// Old variables
const client = sanityClient(sanityConfig);
const sanityData = await client.fetch<SanityPayload>(QUERY_SANITY, {baseUrl});

// New variables
const client = new PicoSanity(sanityConfig)
const sanityData = await client.fetch(QUERY_SANITY, {baseUrl})

Happy building 👍

**Comment by benitodotcool** [comment]
Hello Axel,
Amazing response, I've tried and it's perfectly works!
Thank's. 🤞🏻

@benitodotcool
